import {invoke} from "@tauri-apps/api/core";

// ========== Identity Cache ==========

let cachedIdentity: number[] | null = null;

/**
 * Get the current user's identity (cached after first fetch)
 */
async function getCurrentIdentity(): Promise<number[]> {
  if (cachedIdentity) {
    return cachedIdentity;
  }
  cachedIdentity = await invoke<number[]>("get_current_identity");
  return cachedIdentity;
}

/**
 * Clear the cached identity (call on logout/profile switch)
 */
export function clearIdentityCache(): void {
  cachedIdentity = null;
}

/**
 * Get the current user's identity as a hex string (for comparison with user_id fields)
 */
export async function getCurrentIdentityHex(): Promise<string> {
  const identity = await getCurrentIdentity();
  return identity.map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ========== Types ==========

/**
 * A formatting span within text content.
 * Represents a range of characters with a specific format.
 */
export interface FormatSpan {
  /** Start character index (inclusive) */
  start: number;
  /** End character index (exclusive) */
  end: number;
  /** Format type: "bold", "italic", "underline", "code", "link", "strikethrough" */
  type: string;
  /** URL for link type (optional) */
  url?: string;
}

/**
 * Paragraph block content
 */
export interface ParagraphV1 {
  author: string; // Identity as hex string
  group_id: string;
  group_row: string;
  text: string;
  formatting: FormatSpan[];
}

/**
 * Heading block content
 */
export interface HeadingV1 {
  author: string;
  group_id: string;
  group_row: string;
  text: string;
  level: 1 | 2 | 3 | 4 | 5 | 6;
}

/**
 * Typst block content — raw Typst markup source.
 * Formatting is expressed in Typst syntax, not as separate spans.
 */
export interface TypstV1 {
  author: string;
  group_id: string;
  group_row: string;
  text: string;
}

/**
 * Block content union type
 */
export type BlockContent =
  | ({block_type: "paragraph"; block_type_version: 1} & ParagraphV1)
  | ({block_type: "heading"; block_type_version: 1} & HeadingV1)
  | ({block_type: "typst"; block_type_version: 1} & TypstV1);

/**
 * Full block with metadata
 */
export interface Block {
  id: number;
  timestamp: number;
  deleted?: boolean;
  block_type: string;
  block_type_version: number;
  // Content fields are flattened at the top level
  author: number[]; // 32-byte SpacetimeDB Identity
  group_id: string;
  group_row: string;
  text?: string;
  formatting?: FormatSpan[];
  level?: number;
}

/**
 * Reconstructed block state at a specific timestamp
 */
export interface BlockData {
  timestamp: number;
  block_id: number;
  block: Block;
}

/**
 * Collection of reconstructed blocks for a document
 */
export interface DocumentData {
  doc_id: string;
  blocks: BlockData[];
}

/**
 * Decrypted live block for real-time collaboration
 */
export interface DecryptedLiveBlock {
  live_block_id: string;
  doc_id: string;
  block_id: number;
  user_id: string; // Identity as hex string
  content: Block;
  username: string;
  locked_at: number | null;
}

// ========== Block Service ==========

/**
 * Block Service
 * Wraps Tauri commands for block CRUD and live collaboration operations
 */
export class BlockService {
  // ===== Block CRUD Operations =====

  /**
   * Retrieves blocks at a specific point in document history.
   * @param docId - Document to query
   * @param blockIds - Specific blocks to retrieve (empty for all)
   * @param timestamp - Point in time to reconstruct blocks at (defaults to current time)
   */
  static async getBlocks(
    docId: string,
    blockIds: number[] = [],
    timestamp: number = Date.now()
  ): Promise<DocumentData> {
    return invoke<DocumentData>("get_blocks", {docId, blockIds, timestamp});
  }

  /**
   * Creates a new block in a document.
   * A cryptographically random block ID is automatically generated by the backend.
   * @param docId - Document to add the block to
   * @param block - Block content to create
   * @returns The generated block ID
   */
  static async createBlock(docId: string, block: Block): Promise<number> {
    return invoke<number>("create_block", {docId, block});
  }

  /**
   * Updates an existing block's content.
   * Changes are throttled and batched automatically.
   * @param docId - Document containing the block
   * @param blockId - Block to update
   * @param block - New block content
   */
  static async updateBlock(
    docId: string,
    blockId: number,
    block: Block
  ): Promise<void> {
    await invoke("update_block", {docId, blockId, block});
  }

  /**
   * Soft-deletes a block by marking it as deleted.
   * The block remains in history and can be restored via version tags.
   * @param docId - Document containing the block
   * @param blockId - Block to delete
   */
  static async deleteBlock(docId: string, blockId: number): Promise<void> {
    await invoke("delete_block", {docId, blockId});
  }

  // ===== Live Collaboration Operations =====

  /**
   * Requests a lock on a block for editing.
   * If successful, collaborators will see a solid line indicator.
   * @param docId - Document containing the block
   * @param blockId - Block to lock
   * @param content - Current block content to show collaborators
   * @param username - Display name for the lock indicator
   */
  static async requestLock(
    docId: string,
    blockId: number,
    content: Block,
    username: string
  ): Promise<void> {
    await invoke("request_lock", {docId, blockId, content, username});
  }

  /**
   * Releases lock but keeps focus indicator (dotted line).
   * Call when user stops typing but cursor remains in the block.
   * @param docId - Document containing the block
   * @param blockId - Block to release lock from
   */
  static async releaseLockFocused(
    docId: string,
    blockId: number
  ): Promise<void> {
    await invoke("release_lock_focused", {docId, blockId});
  }

  /**
   * Fully releases lock and removes all indicators.
   * Call when user leaves the block entirely (blur/unfocus).
   * @param docId - Document containing the block
   * @param blockId - Block to release lock from
   */
  static async releaseLockBlur(docId: string, blockId: number): Promise<void> {
    await invoke("release_lock_blur", {docId, blockId});
  }

  /**
   * Gets all active locks on a document.
   * Returns live blocks showing who is editing which blocks.
   * @param docId - Document to query
   */
  static async getDocumentLocks(docId: string): Promise<DecryptedLiveBlock[]> {
    return invoke<DecryptedLiveBlock[]>("get_document_locks", {docId});
  }

  /**
   * Updates live block content for real-time collaboration.
   * This does NOT persist the content - it's purely for showing
   * collaborators what is being typed in real-time.
   * @param docId - Document containing the block
   * @param blockId - Block being edited
   * @param content - Current block content to broadcast
   */
  static async updateLiveBlock(
    docId: string,
    blockId: number,
    content: Block
  ): Promise<void> {
    await invoke("update_live_block", {docId, blockId, content});
  }
}

// ========== Helper Functions ==========

/**
 * Creates a new paragraph block with default values.
 * @param id - Block ID (use 0 for auto-generation)
 * @param text - Initial text content
 * @param groupId - Group ID for ordering (default "main")
 * @param groupRow - Row within group for ordering
 */
export async function createParagraphBlock(
  id: number,
  text: string,
  groupId = "main",
  groupRow = "0"
): Promise<Block> {
  const author = await getCurrentIdentity();
  return {
    id,
    timestamp: Date.now(),
    block_type: "paragraph",
    block_type_version: 1,
    author,
    group_id: groupId,
    group_row: groupRow,
    text,
    formatting: [],
  };
}

/**
 * Creates a new heading block with default values.
 * @param id - Block ID (use 0 for auto-generation)
 * @param text - Heading text content
 * @param level - Heading level (1-6)
 * @param groupId - Group ID for ordering (default "main")
 * @param groupRow - Row within group for ordering
 */
export async function createHeadingBlock(
  id: number,
  text: string,
  level: 1 | 2 | 3 | 4 | 5 | 6 = 1,
  groupId = "main",
  groupRow = "0"
): Promise<Block> {
  const author = await getCurrentIdentity();
  return {
    id,
    timestamp: Date.now(),
    block_type: "heading",
    block_type_version: 1,
    author,
    group_id: groupId,
    group_row: groupRow,
    text,
    level,
  };
}

/**
 * Checks if a block is a paragraph
 */
export function isParagraph(block: Block): boolean {
  return block.block_type === "paragraph";
}

/**
 * Checks if a block is a heading
 */
export function isHeading(block: Block): boolean {
  return block.block_type === "heading";
}

/**
 * Creates a new Typst block with default values.
 * @param id - Block ID (use 0 for auto-generation)
 * @param text - Initial Typst source text
 * @param groupId - Group ID for ordering (default "main")
 * @param groupRow - Row within group for ordering
 */
export async function createTypstBlock(
  id: number,
  text: string,
  groupId = "main",
  groupRow = "0"
): Promise<Block> {
  const author = await getCurrentIdentity();
  return {
    id,
    timestamp: Date.now(),
    block_type: "typst",
    block_type_version: 1,
    author,
    group_id: groupId,
    group_row: groupRow,
    text,
  };
}

/**
 * Checks if a block is a Typst block
 */
export function isTypst(block: Block): boolean {
  return block.block_type === "typst";
}
