[package]
name = "axonotes_stdb"
version = "0.1.0"
description = "SpaceTimeDB module for real-time collaboration with end-to-end encryption and access control"
authors = ["Oliver Seifert <oliver@axonotes.ch>"]
edition = "2021"
license-file = "../LICENSE"
repository = "https://github.com/axonotes/AxonotesCore"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.11.*"
log = "0.4"
ed25519-dalek = {version = "2.2.0", features = ["rand_core"]}
# Must be 0.6.4 for x25519-dalek and ed25519-dalek
rand_core = {version = "0.6.4", features = ["getrandom"]}
uuid = {version = "1.19.0", default-features = false}
blake3 = "1.8.2"
rand = {version = "0.8.5", default-features = false}
