// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AddRowAfter } from "./add_row_after_reducer.ts";
export { AddRowAfter };
import { AddRowToDocument } from "./add_row_to_document_reducer.ts";
export { AddRowToDocument };
import { CreateDocument } from "./create_document_reducer.ts";
export { CreateDocument };
import { DeleteRow } from "./delete_row_reducer.ts";
export { DeleteRow };
import { EditRow } from "./edit_row_reducer.ts";
export { EditRow };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { MergeWithPreviousRow } from "./merge_with_previous_row_reducer.ts";
export { MergeWithPreviousRow };
import { SplitRow } from "./split_row_reducer.ts";
export { SplitRow };
import { StartEdit } from "./start_edit_reducer.ts";
export { StartEdit };
import { StopAllEdits } from "./stop_all_edits_reducer.ts";
export { StopAllEdits };
import { StopEdit } from "./stop_edit_reducer.ts";
export { StopEdit };
import { UpdateDocumentTitle } from "./update_document_title_reducer.ts";
export { UpdateDocumentTitle };

// Import and reexport all table handle types
import { DocumentTableHandle } from "./document_table.ts";
export { DocumentTableHandle };

// Import and reexport all types
import { Document } from "./document_type.ts";
export { Document };
import { DocumentRow } from "./document_row_type.ts";
export { DocumentRow };

const REMOTE_MODULE = {
  tables: {
    document: {
      tableName: "document",
      rowType: Document.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Document.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    add_row_after: {
      reducerName: "add_row_after",
      argsType: AddRowAfter.getTypeScriptAlgebraicType(),
    },
    add_row_to_document: {
      reducerName: "add_row_to_document",
      argsType: AddRowToDocument.getTypeScriptAlgebraicType(),
    },
    create_document: {
      reducerName: "create_document",
      argsType: CreateDocument.getTypeScriptAlgebraicType(),
    },
    delete_row: {
      reducerName: "delete_row",
      argsType: DeleteRow.getTypeScriptAlgebraicType(),
    },
    edit_row: {
      reducerName: "edit_row",
      argsType: EditRow.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    merge_with_previous_row: {
      reducerName: "merge_with_previous_row",
      argsType: MergeWithPreviousRow.getTypeScriptAlgebraicType(),
    },
    split_row: {
      reducerName: "split_row",
      argsType: SplitRow.getTypeScriptAlgebraicType(),
    },
    start_edit: {
      reducerName: "start_edit",
      argsType: StartEdit.getTypeScriptAlgebraicType(),
    },
    stop_all_edits: {
      reducerName: "stop_all_edits",
      argsType: StopAllEdits.getTypeScriptAlgebraicType(),
    },
    stop_edit: {
      reducerName: "stop_edit",
      argsType: StopEdit.getTypeScriptAlgebraicType(),
    },
    update_document_title: {
      reducerName: "update_document_title",
      argsType: UpdateDocumentTitle.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.2.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddRowAfter", args: AddRowAfter }
| { name: "AddRowToDocument", args: AddRowToDocument }
| { name: "CreateDocument", args: CreateDocument }
| { name: "DeleteRow", args: DeleteRow }
| { name: "EditRow", args: EditRow }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "MergeWithPreviousRow", args: MergeWithPreviousRow }
| { name: "SplitRow", args: SplitRow }
| { name: "StartEdit", args: StartEdit }
| { name: "StopAllEdits", args: StopAllEdits }
| { name: "StopEdit", args: StopEdit }
| { name: "UpdateDocumentTitle", args: UpdateDocumentTitle }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addRowAfter(documentId: bigint, afterIndex: number, content: string) {
    const __args = { documentId, afterIndex, content };
    let __writer = new BinaryWriter(1024);
    AddRowAfter.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_row_after", __argsBuffer, this.setCallReducerFlags.addRowAfterFlags);
  }

  onAddRowAfter(callback: (ctx: ReducerEventContext, documentId: bigint, afterIndex: number, content: string) => void) {
    this.connection.onReducer("add_row_after", callback);
  }

  removeOnAddRowAfter(callback: (ctx: ReducerEventContext, documentId: bigint, afterIndex: number, content: string) => void) {
    this.connection.offReducer("add_row_after", callback);
  }

  addRowToDocument(documentId: bigint) {
    const __args = { documentId };
    let __writer = new BinaryWriter(1024);
    AddRowToDocument.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_row_to_document", __argsBuffer, this.setCallReducerFlags.addRowToDocumentFlags);
  }

  onAddRowToDocument(callback: (ctx: ReducerEventContext, documentId: bigint) => void) {
    this.connection.onReducer("add_row_to_document", callback);
  }

  removeOnAddRowToDocument(callback: (ctx: ReducerEventContext, documentId: bigint) => void) {
    this.connection.offReducer("add_row_to_document", callback);
  }

  createDocument(title: string) {
    const __args = { title };
    let __writer = new BinaryWriter(1024);
    CreateDocument.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_document", __argsBuffer, this.setCallReducerFlags.createDocumentFlags);
  }

  onCreateDocument(callback: (ctx: ReducerEventContext, title: string) => void) {
    this.connection.onReducer("create_document", callback);
  }

  removeOnCreateDocument(callback: (ctx: ReducerEventContext, title: string) => void) {
    this.connection.offReducer("create_document", callback);
  }

  deleteRow(documentId: bigint, rowIndex: number) {
    const __args = { documentId, rowIndex };
    let __writer = new BinaryWriter(1024);
    DeleteRow.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_row", __argsBuffer, this.setCallReducerFlags.deleteRowFlags);
  }

  onDeleteRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.onReducer("delete_row", callback);
  }

  removeOnDeleteRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.offReducer("delete_row", callback);
  }

  editRow(documentId: bigint, rowIndex: number, newContent: string) {
    const __args = { documentId, rowIndex, newContent };
    let __writer = new BinaryWriter(1024);
    EditRow.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("edit_row", __argsBuffer, this.setCallReducerFlags.editRowFlags);
  }

  onEditRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number, newContent: string) => void) {
    this.connection.onReducer("edit_row", callback);
  }

  removeOnEditRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number, newContent: string) => void) {
    this.connection.offReducer("edit_row", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  mergeWithPreviousRow(documentId: bigint, rowIndex: number) {
    const __args = { documentId, rowIndex };
    let __writer = new BinaryWriter(1024);
    MergeWithPreviousRow.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("merge_with_previous_row", __argsBuffer, this.setCallReducerFlags.mergeWithPreviousRowFlags);
  }

  onMergeWithPreviousRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.onReducer("merge_with_previous_row", callback);
  }

  removeOnMergeWithPreviousRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.offReducer("merge_with_previous_row", callback);
  }

  splitRow(documentId: bigint, rowIndex: number, splitPosition: number) {
    const __args = { documentId, rowIndex, splitPosition };
    let __writer = new BinaryWriter(1024);
    SplitRow.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("split_row", __argsBuffer, this.setCallReducerFlags.splitRowFlags);
  }

  onSplitRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number, splitPosition: number) => void) {
    this.connection.onReducer("split_row", callback);
  }

  removeOnSplitRow(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number, splitPosition: number) => void) {
    this.connection.offReducer("split_row", callback);
  }

  startEdit(documentId: bigint, rowIndex: number) {
    const __args = { documentId, rowIndex };
    let __writer = new BinaryWriter(1024);
    StartEdit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_edit", __argsBuffer, this.setCallReducerFlags.startEditFlags);
  }

  onStartEdit(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.onReducer("start_edit", callback);
  }

  removeOnStartEdit(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.offReducer("start_edit", callback);
  }

  stopAllEdits() {
    this.connection.callReducer("stop_all_edits", new Uint8Array(0), this.setCallReducerFlags.stopAllEditsFlags);
  }

  onStopAllEdits(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("stop_all_edits", callback);
  }

  removeOnStopAllEdits(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("stop_all_edits", callback);
  }

  stopEdit(documentId: bigint, rowIndex: number) {
    const __args = { documentId, rowIndex };
    let __writer = new BinaryWriter(1024);
    StopEdit.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("stop_edit", __argsBuffer, this.setCallReducerFlags.stopEditFlags);
  }

  onStopEdit(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.onReducer("stop_edit", callback);
  }

  removeOnStopEdit(callback: (ctx: ReducerEventContext, documentId: bigint, rowIndex: number) => void) {
    this.connection.offReducer("stop_edit", callback);
  }

  updateDocumentTitle(documentId: bigint, newTitle: string) {
    const __args = { documentId, newTitle };
    let __writer = new BinaryWriter(1024);
    UpdateDocumentTitle.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_document_title", __argsBuffer, this.setCallReducerFlags.updateDocumentTitleFlags);
  }

  onUpdateDocumentTitle(callback: (ctx: ReducerEventContext, documentId: bigint, newTitle: string) => void) {
    this.connection.onReducer("update_document_title", callback);
  }

  removeOnUpdateDocumentTitle(callback: (ctx: ReducerEventContext, documentId: bigint, newTitle: string) => void) {
    this.connection.offReducer("update_document_title", callback);
  }

}

export class SetReducerFlags {
  addRowAfterFlags: CallReducerFlags = 'FullUpdate';
  addRowAfter(flags: CallReducerFlags) {
    this.addRowAfterFlags = flags;
  }

  addRowToDocumentFlags: CallReducerFlags = 'FullUpdate';
  addRowToDocument(flags: CallReducerFlags) {
    this.addRowToDocumentFlags = flags;
  }

  createDocumentFlags: CallReducerFlags = 'FullUpdate';
  createDocument(flags: CallReducerFlags) {
    this.createDocumentFlags = flags;
  }

  deleteRowFlags: CallReducerFlags = 'FullUpdate';
  deleteRow(flags: CallReducerFlags) {
    this.deleteRowFlags = flags;
  }

  editRowFlags: CallReducerFlags = 'FullUpdate';
  editRow(flags: CallReducerFlags) {
    this.editRowFlags = flags;
  }

  mergeWithPreviousRowFlags: CallReducerFlags = 'FullUpdate';
  mergeWithPreviousRow(flags: CallReducerFlags) {
    this.mergeWithPreviousRowFlags = flags;
  }

  splitRowFlags: CallReducerFlags = 'FullUpdate';
  splitRow(flags: CallReducerFlags) {
    this.splitRowFlags = flags;
  }

  startEditFlags: CallReducerFlags = 'FullUpdate';
  startEdit(flags: CallReducerFlags) {
    this.startEditFlags = flags;
  }

  stopAllEditsFlags: CallReducerFlags = 'FullUpdate';
  stopAllEdits(flags: CallReducerFlags) {
    this.stopAllEditsFlags = flags;
  }

  stopEditFlags: CallReducerFlags = 'FullUpdate';
  stopEdit(flags: CallReducerFlags) {
    this.stopEditFlags = flags;
  }

  updateDocumentTitleFlags: CallReducerFlags = 'FullUpdate';
  updateDocumentTitle(flags: CallReducerFlags) {
    this.updateDocumentTitleFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get document(): DocumentTableHandle {
    return new DocumentTableHandle(this.connection.clientCache.getOrCreateTable<Document>(REMOTE_MODULE.tables.document));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
