[app]
name="AxonotesApp"
version="0.0.1"
environment="development"

[oauth]
client_id="client_01JX2EAD13T3F7W9K57M08ZT58"
authorization_url="https://api.workos.com/user_management/authorize"
token_url="https://api.workos.com/user_management/authenticate"
redirect_uri="http://localhost:8080/callback"
callback_port=8080
provider="authkit"
scopes=["profile", "email"]

[stdb]
default_host_uri="http://localhost:3000"
default_module_name="axonotes"

[storage]
api_port=8081
minio_api_port=9000
minio_console_port=9001