// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
    AlgebraicType,
    AlgebraicValue,
    BinaryReader,
    BinaryWriter,
    ConnectionId,
    DbConnectionBuilder,
    DbConnectionImpl,
    Identity,
    ProductType,
    ProductTypeElement,
    SubscriptionBuilderImpl,
    SumType,
    SumTypeVariant,
    TableCache,
    TimeDuration,
    Timestamp,
    deepEqual,
    type CallReducerFlags,
    type DbContext,
    type ErrorContextInterface,
    type Event,
    type EventContextInterface,
    type ReducerEventContextInterface,
    type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type ClientConnected = {};

/**
 * A namespace for generated helper functions.
 */
export namespace ClientConnected {
    /**
     * Returns the AlgebraicType representation for this type.
     *
     * The returned AlgebraicType is a product type with no fields (an empty/unit product).
     *
     * @returns The AlgebraicType for this type
     */
    export function getTypeScriptAlgebraicType(): AlgebraicType {
        return AlgebraicType.createProductType([]);
    }

    /**
     * Serializes a ClientConnected value into the provided binary writer.
     *
     * Uses the generated TypeScript AlgebraicType for ClientConnected (an empty product type)
     * to perform the serialization.
     *
     * @param value - The ClientConnected value to serialize (empty object)
     */
    export function serialize(
        writer: BinaryWriter,
        value: ClientConnected
    ): void {
        ClientConnected.getTypeScriptAlgebraicType().serialize(writer, value);
    }

    /**
     * Deserializes a ClientConnected value from a binary stream.
     *
     * @param reader - Binary reader positioned at a serialized ClientConnected value.
     * @returns The deserialized ClientConnected (an empty object).
     */
    export function deserialize(reader: BinaryReader): ClientConnected {
        return ClientConnected.getTypeScriptAlgebraicType().deserialize(reader);
    }
}
