// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
    AlgebraicType,
    AlgebraicValue,
    BinaryReader,
    BinaryWriter,
    ConnectionId,
    DbConnectionBuilder,
    DbConnectionImpl,
    Identity,
    ProductType,
    ProductTypeElement,
    SubscriptionBuilderImpl,
    SumType,
    SumTypeVariant,
    TableCache,
    TimeDuration,
    Timestamp,
    deepEqual,
    type CallReducerFlags,
    type DbContext,
    type ErrorContextInterface,
    type Event,
    type EventContextInterface,
    type ReducerEventContextInterface,
    type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type InitEncryptionAndSigning = {
    publicKey: string;
    encryptedPrivateKey: string;
    encryptedBackupKey: string;
    publicSigningKey: string;
    encryptedPrivateSigningKey: string;
    encryptedPrivateBackupSigningKey: string;
    argonSalt: string;
};

/**
 * A namespace for generated helper functions.
 */
export namespace InitEncryptionAndSigning {
    /**
     * A function which returns this type represented as an AlgebraicType.
     * This function is derived from the AlgebraicType used to generate this type.
     */
    export function getTypeScriptAlgebraicType(): AlgebraicType {
        return AlgebraicType.createProductType([
            new ProductTypeElement(
                "publicKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "encryptedPrivateKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "encryptedBackupKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "publicSigningKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "encryptedPrivateSigningKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "encryptedPrivateBackupSigningKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "argonSalt",
                AlgebraicType.createStringType()
            ),
        ]);
    }

    /**
     * Serializes an InitEncryptionAndSigning value into a binary writer.
     *
     * @param value - The InitEncryptionAndSigning object to serialize.
     */
    export function serialize(
        writer: BinaryWriter,
        value: InitEncryptionAndSigning
    ): void {
        InitEncryptionAndSigning.getTypeScriptAlgebraicType().serialize(
            writer,
            value
        );
    }

    /**
     * Reads and returns an InitEncryptionAndSigning value from the provided binary reader.
     *
     * @returns The deserialized InitEncryptionAndSigning object.
     */
    export function deserialize(
        reader: BinaryReader
    ): InitEncryptionAndSigning {
        return InitEncryptionAndSigning.getTypeScriptAlgebraicType().deserialize(
            reader
        );
    }
}
