// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
    AlgebraicType,
    AlgebraicValue,
    BinaryReader,
    BinaryWriter,
    ConnectionId,
    DbConnectionBuilder,
    DbConnectionImpl,
    Identity,
    ProductType,
    ProductTypeElement,
    SubscriptionBuilderImpl,
    SumType,
    SumTypeVariant,
    TableCache,
    TimeDuration,
    Timestamp,
    deepEqual,
    type CallReducerFlags,
    type DbContext,
    type ErrorContextInterface,
    type Event,
    type EventContextInterface,
    type ReducerEventContextInterface,
    type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type UpdateEncryptionKeys = {
    newEncryptedPrivateKey: string;
    newEncryptedPrivateSigningKey: string;
    newArgonSalt: string;
    signatureBase64: string;
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpdateEncryptionKeys {
    /**
     * Return an AlgebraicType describing the UpdateEncryptionKeys product type.
     *
     * The resulting product type has four string fields:
     * - `newEncryptedPrivateKey`
     * - `newEncryptedPrivateSigningKey`
     * - `newArgonSalt`
     * - `signatureBase64`
     *
     * @returns An AlgebraicType representing the UpdateEncryptionKeys structure.
     */
    export function getTypeScriptAlgebraicType(): AlgebraicType {
        return AlgebraicType.createProductType([
            new ProductTypeElement(
                "newEncryptedPrivateKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "newEncryptedPrivateSigningKey",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "newArgonSalt",
                AlgebraicType.createStringType()
            ),
            new ProductTypeElement(
                "signatureBase64",
                AlgebraicType.createStringType()
            ),
        ]);
    }

    /**
     * Writes an UpdateEncryptionKeys value to a BinaryWriter as its binary representation.
     *
     * Delegates to the generated algebraic type serializer for the UpdateEncryptionKeys product type;
     * the provided `writer` will be advanced with the serialized bytes for `value`.
     *
     * @param value - The UpdateEncryptionKeys object to serialize.
     */
    export function serialize(
        writer: BinaryWriter,
        value: UpdateEncryptionKeys
    ): void {
        UpdateEncryptionKeys.getTypeScriptAlgebraicType().serialize(
            writer,
            value
        );
    }

    /**
     * Deserializes an UpdateEncryptionKeys value from a BinaryReader.
     *
     * @returns The deserialized UpdateEncryptionKeys object.
     */
    export function deserialize(reader: BinaryReader): UpdateEncryptionKeys {
        return UpdateEncryptionKeys.getTypeScriptAlgebraicType().deserialize(
            reader
        );
    }
}
