// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
    AlgebraicType,
    AlgebraicValue,
    BinaryReader,
    BinaryWriter,
    ConnectionId,
    DbConnectionBuilder,
    DbConnectionImpl,
    Identity,
    ProductType,
    ProductTypeElement,
    SubscriptionBuilderImpl,
    SumType,
    SumTypeVariant,
    TableCache,
    TimeDuration,
    Timestamp,
    deepEqual,
    type CallReducerFlags,
    type DbContext,
    type ErrorContextInterface,
    type Event,
    type EventContextInterface,
    type ReducerEventContextInterface,
    type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type User = {
    identity: Identity;
    publicKey: string | undefined;
    encryptedPrivateKey: string | undefined;
    encryptedBackupKey: string | undefined;
    publicSigningKey: string | undefined;
    encryptedPrivateSigningKey: string | undefined;
    encryptedPrivateBackupSigningKey: string | undefined;
    argonSalt: string | undefined;
};

/**
 * A namespace for generated helper functions.
 */
export namespace User {
    /**
     * Returns an AlgebraicType describing the User product type.
     *
     * The returned product type has eight elements (in order):
     *  - `identity`: Identity
     *  - `publicKey`: optional string
     *  - `encryptedPrivateKey`: optional string
     *  - `encryptedBackupKey`: optional string
     *  - `publicSigningKey`: optional string
     *  - `encryptedPrivateSigningKey`: optional string
     *  - `encryptedPrivateBackupSigningKey`: optional string
     *  - `argonSalt`: optional string
     *
     * @returns An AlgebraicType representing the TypeScript `User` product type.
     */
    export function getTypeScriptAlgebraicType(): AlgebraicType {
        return AlgebraicType.createProductType([
            new ProductTypeElement(
                "identity",
                AlgebraicType.createIdentityType()
            ),
            new ProductTypeElement(
                "publicKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "encryptedPrivateKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "encryptedBackupKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "publicSigningKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "encryptedPrivateSigningKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "encryptedPrivateBackupSigningKey",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
            new ProductTypeElement(
                "argonSalt",
                AlgebraicType.createOptionType(AlgebraicType.createStringType())
            ),
        ]);
    }

    /**
     * Serializes a User value into a BinaryWriter.
     *
     * Writes the User to the provided writer using the generated algebraic-type representation.
     */
    export function serialize(writer: BinaryWriter, value: User): void {
        User.getTypeScriptAlgebraicType().serialize(writer, value);
    }

    /**
     * Deserializes a User from the given binary reader.
     *
     * @param reader - BinaryReader positioned at the start of a serialized `User` value
     * @returns The deserialized `User`
     */
    export function deserialize(reader: BinaryReader): User {
        return User.getTypeScriptAlgebraicType().deserialize(reader);
    }
}
