import {cmd, liveExec} from "@axonotes/axogen";
import {throwIfToolMissing} from "../utils/tool-detection";

export const dev2Cmd = cmd({
  help: "Start a second Axonotes instance with separate data directory (for multi-user testing)",
  exec: async () => {
    await throwIfToolMissing("Bun", "bun", "--version", "https://bun.sh/");
    await throwIfToolMissing(
      "Cargo",
      "cargo",
      "--version",
      "https://rustup.rs/"
    );

    // DON'T Re-generate Rust bindings before starting dev server, so dev1 doesn't get interrupted
    // For this to work, the bindings must have already been generated by dev1
    // await generateRustBindings();

    const isLinux = process.platform === "linux";
    const command = `${isLinux ? "WEBKIT_DISABLE_DMABUF_RENDERER=1 " : ""}bun run tauri dev --config "src-tauri/tauri.dev2.conf.json"`;
    await liveExec(command, {
      cwd: "./axonotes-app",
      outputPrefix: "DEV2",
    });
  },
});
