import {generateKeyPairSync} from "node:crypto";
import {readFileSync, writeFileSync, existsSync, appendFileSync} from "node:fs";
import {resolve} from "node:path";
import {config} from "dotenv";
import type {
    JWTKeys,
    ConfigDefinition,
    BuiltinFunctions,
    EnvironmentState,
} from "./types.js";

const envPath = resolve(".env");
config({path: envPath});

export const env: Record<string, string | undefined> = process.env;

export function generateJwtKeys(): JWTKeys {
    if (existsSync(envPath)) {
        const envContent = readFileSync(envPath, "utf-8");

        const privateKeyMatch = envContent.match(
            /^JWT_PRIVATE_KEY_BASE64\s*=\s*"?([^"\n\r]+)"?\s*$/m
        );
        const publicKeyMatch = envContent.match(
            /^JWT_PUBLIC_KEY_BASE64\s*=\s*"?([^"\n\r]+)"?\s*$/m
        );
        const keyIdMatch = envContent.match(
            /^JWT_KEY_ID\s*=\s*"?([^"\n\r]+)"?\s*$/m
        );

        if (privateKeyMatch && publicKeyMatch && keyIdMatch) {
            return {
                privateKey: privateKeyMatch[1],
                publicKey: publicKeyMatch[1],
                keyId: keyIdMatch[1],
            };
        }
    }

    console.log("🔑 Generating new ECDSA (ES256) key pair...");

    const {privateKey, publicKey} = generateKeyPairSync("ec", {
        namedCurve: "prime256v1",
        publicKeyEncoding: {type: "spki", format: "pem"},
        privateKeyEncoding: {type: "pkcs8", format: "pem"},
    });

    const privateKeyBase64 = Buffer.from(privateKey).toString("base64");
    const publicKeyBase64 = Buffer.from(publicKey).toString("base64");
    const keyId = `axonotes-key-${new Date().toISOString().slice(0, 10)}`;

    const keys = {
        privateKey: privateKeyBase64,
        publicKey: publicKeyBase64,
        keyId,
    };

    updateEnvFile(keys);

    console.log("   ✅ JWT keys generated and saved to .env");

    return keys;
}

function updateEnvFile(keys: JWTKeys): void {
    if (existsSync(envPath)) {
        let envContent = readFileSync(envPath, "utf-8");

        const keyEntries = [
            {key: "JWT_PRIVATE_KEY_BASE64", value: keys.privateKey},
            {key: "JWT_PUBLIC_KEY_BASE64", value: keys.publicKey},
            {key: "JWT_KEY_ID", value: keys.keyId},
        ];

        let hasUpdates = false;

        for (const {key, value} of keyEntries) {
            const regex = new RegExp(`^(${key}=)(.*)$`, "m");
            if (regex.test(envContent)) {
                envContent = envContent.replace(regex, `$1"${value}"`);
                hasUpdates = true;
            } else {
                if (!hasUpdates) {
                    envContent += "\n\n# JWT Keys (auto-generated)\n";
                }
                envContent += `${key}="${value}"\n`;
                hasUpdates = true;
            }
        }

        if (hasUpdates) {
            writeFileSync(envPath, envContent);
        }
    } else {
        const envContent = `# WorkOS Configuration
WORKOS_CLIENT_ID=""
WORKOS_API_KEY=""

# JWT Keys (auto-generated)
JWT_PRIVATE_KEY_BASE64="${keys.privateKey}"
JWT_PUBLIC_KEY_BASE64="${keys.publicKey}"
JWT_KEY_ID="${keys.keyId}"
`;

        writeFileSync(envPath, envContent);
        console.log("📄 Created new .env file with JWT keys");
    }
}

export function ensureEnvironmentSetup(configContent?: string): void {
    const usedEnvVars = configContent
        ? extractEnvVariablesFromConfig(configContent)
        : [];

    if (!existsSync(envPath)) {
        console.log("📄 Creating .env file...");
        createEnvFileWithDiscoveredVars(usedEnvVars);
    } else {
        console.log("🔍 Checking environment variables...");
        updateEnvFileWithMissingVars(usedEnvVars);
    }

    runAutoGenerators();
}

function extractEnvVariablesFromConfig(configContent: string): string[] {
    const envVarPattern = /env\.([A-Z_][A-Z0-9_]*)/g;
    const matches = configContent.matchAll(envVarPattern);
    const envVars = new Set<string>();

    for (const match of matches) {
        envVars.add(match[1]);
    }

    return Array.from(envVars).sort();
}

function createEnvFileWithDiscoveredVars(usedEnvVars: string[]): void {
    const envContent = [
        "# Generated by axonotes config system",
        "# Configure the following variables as needed:",
        "",
    ];

    for (const varName of usedEnvVars) {
        const placeholder = getPlaceholderForVar(varName);
        envContent.push(`${varName}=${placeholder}`);
    }

    envContent.push("");
    writeFileSync(envPath, envContent.join("\n"));
    console.log(`📄 Created .env with ${usedEnvVars.length} variables`);
}

function updateEnvFileWithMissingVars(usedEnvVars: string[]): void {
    const envContent = readFileSync(envPath, "utf-8");
    const existingVars = new Set<string>();

    for (const line of envContent.split("\n")) {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)\s*=/);
        if (match) {
            existingVars.add(match[1]);
        }
    }

    const missingVars = usedEnvVars.filter(
        (varName) => !existingVars.has(varName)
    );

    if (missingVars.length > 0) {
        console.log(
            `📝 Adding ${missingVars.length} missing environment variables...`
        );

        let updatedContent = envContent;
        if (!updatedContent.endsWith("\n")) {
            updatedContent += "\n";
        }

        updatedContent += "\n# Added by axonotes config system\n";
        for (const varName of missingVars) {
            const placeholder = getPlaceholderForVar(varName);
            updatedContent += `${varName}=${placeholder}\n`;
            console.log(`   + ${varName}`);
        }

        writeFileSync(envPath, updatedContent);
    }
}

function getPlaceholderForVar(varName: string): string {
    if (varName.includes("JWT")) {
        return '"[AUTO-GENERATED]"';
    }
    if (varName.includes("PORT")) {
        return '"3000"';
    }
    if (
        varName.includes("ORIGIN") ||
        varName.includes("URL") ||
        varName.includes("ENDPOINT")
    ) {
        return '"http://localhost:3000"';
    }
    return '""';
}

function runAutoGenerators(): void {
    const envContent = readFileSync(envPath, "utf-8");
    const needsJwtKeys =
        /JWT_PRIVATE_KEY_BASE64\s*=\s*("\[AUTO-GENERATED\]"|""|''|$)/m.test(
            envContent
        );

    if (needsJwtKeys) {
        console.log("🔑 Generating JWT keys...");
        generateJwtKeys();
    }
}

export function defineConfig(config: ConfigDefinition): ConfigDefinition {
    return config;
}

// Time utility functions for better readability
export const seconds = (value: number): string => (value * 1000).toString();
export const minutes = (value: number): string =>
    (value * 60 * 1000).toString();
export const hours = (value: number): string =>
    (value * 60 * 60 * 1000).toString();
export const days = (value: number): string =>
    (value * 24 * 60 * 60 * 1000).toString();

export const builtinFunctions: BuiltinFunctions = {
    env,
    generateJwtKeys,
    defineConfig,
};
