import {writeFileSync, mkdirSync, existsSync, readFileSync} from "node:fs";
import {dirname, resolve} from "node:path";
import {dump as yamlDump} from "js-yaml";
import {stringify as tomlStringify} from "@iarna/toml";
import {configure as configureNunjucks} from "nunjucks";
import type {
    TargetConfig,
    FileGenerationResult,
    GenerationResult,
    TemplateContext,
    FileHeader,
    ConfigDefinition,
} from "./types.js";

export class FileGenerator {
    private nunjucks: any;

    constructor() {
        this.nunjucks = configureNunjucks(".", {
            autoescape: false,
            throwOnUndefined: true,
        });
    }

    async generateAll(config: ConfigDefinition): Promise<GenerationResult> {
        const results: FileGenerationResult[] = [];
        const errors: string[] = [];

        for (const [name, target] of Object.entries(config.targets)) {
            try {
                const result = await this.generateTarget(
                    name,
                    target,
                    config.globals || {}
                );
                results.push(result);
            } catch (error) {
                const errorMsg =
                    error instanceof Error ? error.message : String(error);
                errors.push(`Failed to generate target '${name}': ${errorMsg}`);
                results.push({
                    path: target.path,
                    success: false,
                    error: errorMsg,
                });
            }
        }

        return {
            success: errors.length === 0,
            results,
            errors,
        };
    }

    async generateTarget(
        name: string,
        target: TargetConfig,
        globals: Record<string, any>
    ): Promise<FileGenerationResult> {
        const targetPath = resolve(target.path);
        const existed = existsSync(targetPath);

        try {
            this.ensureDirectoryExists(targetPath);

            const content = await this.generateContent(target, globals);
            writeFileSync(targetPath, content, "utf-8");

            return {
                path: targetPath,
                success: true,
                created: !existed,
                updated: existed,
            };
        } catch (error) {
            const errorMsg =
                error instanceof Error ? error.message : String(error);
            return {
                path: targetPath,
                success: false,
                error: errorMsg,
            };
        }
    }

    private async generateContent(
        target: TargetConfig,
        globals: Record<string, any>
    ): Promise<string> {
        const context: TemplateContext = {
            variables: target.variables,
            globals,
            timestamp: new Date().toISOString(),
            generatedNotice: "Generated by axonotes config system",
        };

        switch (target.type) {
            case "env":
                return this.generateEnvFile(context);
            case "json":
                return this.generateJsonFile(context);
            case "toml":
                return this.generateTomlFile(context);
            case "yaml":
                return this.generateYamlFile(context);
            case "template":
                return this.generateTemplateFile(target, context);
            default:
                throw new Error(`Unsupported file type: ${target.type}`);
        }
    }

    private generateEnvFile(context: TemplateContext): string {
        const header = this.generateFileHeader("#", context);
        const variables = this.flattenVariables({
            ...context.globals,
            ...context.variables,
        });

        const envLines = Object.entries(variables).map(([key, value]) => {
            const stringValue = this.formatEnvValue(value);
            return `${key}=${stringValue}`;
        });

        return [header, "", ...envLines, ""].join("\n");
    }

    private generateJsonFile(context: TemplateContext): string {
        const jsonObject = {
            _comment_1: `Generated by axonotes config system on ${context.timestamp}`,
            _comment_2: "DO NOT EDIT - changes will be overwritten",
            _comment_3: "Source: axonotes.config.ts",
            ...context.globals,
            ...context.variables,
        };

        return JSON.stringify(jsonObject, null, 2) + "\n";
    }

    private generateTomlFile(context: TemplateContext): string {
        const header = this.generateFileHeader("#", context);
        const variables = {...context.globals, ...context.variables};

        const tomlContent = tomlStringify(variables);
        return [header, "", tomlContent].join("\n");
    }

    private generateYamlFile(context: TemplateContext): string {
        const header = this.generateFileHeader("#", context);
        const variables = {...context.globals, ...context.variables};

        const yamlContent = yamlDump(variables, {
            indent: 2,
            lineWidth: 120,
            noRefs: true,
        });

        return [header, "", yamlContent].join("\n");
    }

    private generateTemplateFile(
        target: TargetConfig,
        context: TemplateContext
    ): string {
        if (!target.template) {
            throw new Error("Template file path is required for template type");
        }

        const templatePath = resolve(target.template);
        if (!existsSync(templatePath)) {
            throw new Error(`Template file not found: ${templatePath}`);
        }

        const templateContent = readFileSync(templatePath, "utf-8");

        const templateData = {
            ...context.globals,
            ...context.variables,
            _timestamp: context.timestamp,
            _generated_notice: context.generatedNotice,
        };

        return this.nunjucks.renderString(templateContent, templateData);
    }

    private generateFileHeader(
        commentChar: string,
        context: TemplateContext
    ): string {
        return [
            `${commentChar} Generated by axonotes config system on ${context.timestamp}`,
            `${commentChar} DO NOT EDIT - changes will be overwritten`,
            `${commentChar} Source: axonotes.config.ts`,
        ].join("\n");
    }

    private flattenVariables(
        obj: Record<string, any>,
        prefix = ""
    ): Record<string, any> {
        const result: Record<string, any> = {};

        for (const [key, value] of Object.entries(obj)) {
            const newKey = prefix ? `${prefix}_${key}` : key;

            if (
                value !== null &&
                typeof value === "object" &&
                !Array.isArray(value)
            ) {
                Object.assign(result, this.flattenVariables(value, newKey));
            } else {
                result[newKey] = value;
            }
        }

        return result;
    }

    private formatEnvValue(value: any): string {
        if (typeof value === "string") {
            if (
                value.includes(" ") ||
                value.includes('"') ||
                value.includes("'")
            ) {
                return `"${value.replace(/"/g, '\\"')}"`;
            }
            return value;
        }

        if (typeof value === "boolean") {
            return value ? "true" : "false";
        }

        if (typeof value === "number") {
            return value.toString();
        }

        if (value === null || value === undefined) {
            return "";
        }

        return String(value);
    }

    private ensureDirectoryExists(filePath: string): void {
        const dir = dirname(filePath);
        if (!existsSync(dir)) {
            mkdirSync(dir, {recursive: true});
        }
    }
}
