// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(
    __lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug,
)]
#[sats(crate = __lib)]
pub(super) struct InitEncryptionAndSigningArgs {
    pub public_key: String,
    pub encrypted_private_key: String,
    pub encrypted_backup_key: String,
    pub public_signing_key: String,
    pub encrypted_private_signing_key: String,
    pub encrypted_private_backup_signing_key: String,
    pub argon_salt: String,
}

impl From<InitEncryptionAndSigningArgs> for super::Reducer {
    /// Converts an `InitEncryptionAndSigningArgs` value into a `Reducer::InitEncryptionAndSigning` variant,
    /// moving all argument fields into the reducer payload.
    ///
    /// # Examples
    ///
    /// ```
    /// let args = InitEncryptionAndSigningArgs {
    ///     public_key: String::from("pub"),
    ///     encrypted_private_key: String::from("enc_priv"),
    ///     encrypted_backup_key: String::from("enc_backup"),
    ///     public_signing_key: String::from("pub_sign"),
    ///     encrypted_private_signing_key: String::from("enc_priv_sign"),
    ///     encrypted_private_backup_signing_key: String::from("enc_priv_backup_sign"),
    ///     argon_salt: String::from("salt"),
    /// };
    /// let reducer: super::Reducer = args.into();
    /// match reducer {
    ///     super::Reducer::InitEncryptionAndSigning { public_key, .. } => assert_eq!(public_key, "pub"),
    ///     _ => panic!("unexpected reducer variant"),
    /// }
    /// ```
    fn from(args: InitEncryptionAndSigningArgs) -> Self {
        Self::InitEncryptionAndSigning {
            public_key: args.public_key,
            encrypted_private_key: args.encrypted_private_key,
            encrypted_backup_key: args.encrypted_backup_key,
            public_signing_key: args.public_signing_key,
            encrypted_private_signing_key: args.encrypted_private_signing_key,
            encrypted_private_backup_signing_key: args
                .encrypted_private_backup_signing_key,
            argon_salt: args.argon_salt,
        }
    }
}

impl __sdk::InModule for InitEncryptionAndSigningArgs {
    type Module = super::RemoteModule;
}

pub struct InitEncryptionAndSigningCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `init_encryption_and_signing`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait init_encryption_and_signing {
    /// Request that the remote module invoke the reducer `init_encryption_and_signing` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_init_encryption_and_signing`] callbacks.
    fn init_encryption_and_signing(
        &self,
        public_key: String,
        encrypted_private_key: String,
        encrypted_backup_key: String,
        public_signing_key: String,
        encrypted_private_signing_key: String,
        encrypted_private_backup_signing_key: String,
        argon_salt: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `init_encryption_and_signing`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InitEncryptionAndSigningCallbackId`] can be passed to [`Self::remove_on_init_encryption_and_signing`]
    /// to cancel the callback.
    fn on_init_encryption_and_signing(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> InitEncryptionAndSigningCallbackId;
    /// Cancel a callback previously registered by [`Self::on_init_encryption_and_signing`],
    /// causing it not to run in the future.
    fn remove_on_init_encryption_and_signing(
        &self,
        callback: InitEncryptionAndSigningCallbackId,
    );
}

impl init_encryption_and_signing for super::RemoteReducers {
    /// Requests the remote `init_encryption_and_signing` reducer with the given keys and salt.
    ///
    /// Sends a reducer invocation to the remote module carrying the provided payload. The call
    /// returns immediately; the `Ok(())` result only indicates the request was sent successfully,
    /// not that the reducer has completed.
    ///
    /// # Examples
    ///
    /// ```
    /// // `r` is a RemoteReducers implementation.
    /// let _ = r.init_encryption_and_signing(
    ///     "pub_key".to_string(),
    ///     "enc_priv_key".to_string(),
    ///     "enc_backup_key".to_string(),
    ///     "pub_sign_key".to_string(),
    ///     "enc_priv_sign_key".to_string(),
    ///     "enc_priv_backup_sign_key".to_string(),
    ///     "argon_salt".to_string(),
    /// );
    /// ```
    fn init_encryption_and_signing(
        &self,
        public_key: String,
        encrypted_private_key: String,
        encrypted_backup_key: String,
        public_signing_key: String,
        encrypted_private_signing_key: String,
        encrypted_private_backup_signing_key: String,
        argon_salt: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "init_encryption_and_signing",
            InitEncryptionAndSigningArgs {
                public_key,
                encrypted_private_key,
                encrypted_backup_key,
                public_signing_key,
                encrypted_private_signing_key,
                encrypted_private_backup_signing_key,
                argon_salt,
            },
        )
    }
    /// Register a callback invoked when the `init_encryption_and_signing` reducer is emitted.
    ///
    /// The provided callback is called with:
    /// - a reference to the reducer event context, and
    /// - references to the reducer payload fields in this order:
    ///   `public_key`, `encrypted_private_key`, `encrypted_backup_key`,
    ///   `public_signing_key`, `encrypted_private_signing_key`,
    ///   `encrypted_private_backup_signing_key`, `argon_salt`.
    ///
    /// Returns an `InitEncryptionAndSigningCallbackId` that can be used to remove the callback.
    ///
    /// # Examples
    ///
    /// ```
    /// // Register a callback that logs the public and signing keys.
    /// let _cb_id = remote_reducers.on_init_encryption_and_signing(|ctx, public_key, _enc_priv, _enc_backup, public_signing_key, _enc_priv_sign, _enc_priv_backup_sign, _argon_salt| {
    ///     println!("Reducer invoked for public key: {}", public_key);
    ///     println!("Signing key: {}", public_signing_key);
    ///     // `ctx` can be used to inspect metadata about the event.
    /// });
    /// ```
    fn on_init_encryption_and_signing(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> InitEncryptionAndSigningCallbackId {
        InitEncryptionAndSigningCallbackId(self.imp.on_reducer(
            "init_encryption_and_signing",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::InitEncryptionAndSigning {
                                    public_key,
                                    encrypted_private_key,
                                    encrypted_backup_key,
                                    public_signing_key,
                                    encrypted_private_signing_key,
                                    encrypted_private_backup_signing_key,
                                    argon_salt,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    public_key,
                    encrypted_private_key,
                    encrypted_backup_key,
                    public_signing_key,
                    encrypted_private_signing_key,
                    encrypted_private_backup_signing_key,
                    argon_salt,
                )
            }),
        ))
    }
    /// Unregisters a previously registered `on_init_encryption_and_signing` callback.
    ///
    /// This removes the callback identified by `callback` so it will no longer be invoked
    /// when the `init_encryption_and_signing` reducer runs.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// # use app::module_bindings::init_encryption_and_signing::InitEncryptionAndSigningCallbackId;
    /// # // `reducers` represents a value implementing the RemoteReducers extension.
    /// # let reducers = todo!();
    /// # let cb_id: InitEncryptionAndSigningCallbackId = todo!();
    /// reducers.remove_on_init_encryption_and_signing(cb_id);
    /// ```
    fn remove_on_init_encryption_and_signing(
        &self,
        callback: InitEncryptionAndSigningCallbackId,
    ) {
        self.imp
            .remove_on_reducer("init_encryption_and_signing", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `init_encryption_and_signing`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_init_encryption_and_signing {
    /// Set the call-reducer flags for the reducer `init_encryption_and_signing` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn init_encryption_and_signing(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_init_encryption_and_signing for super::SetReducerFlags {
    /// Set call-reducer flags for the `init_encryption_and_signing` reducer.
    ///
    /// The provided `flags` are forwarded to the runtime and control how the
    /// `init_encryption_and_signing` reducer will be scheduled/executed.
    ///
    /// # Examples
    ///
    /// ```
    /// // `setter` implements `SetReducerFlags`
    /// setter.init_encryption_and_signing(__ws::CallReducerFlags::default());
    /// ```
    fn init_encryption_and_signing(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("init_encryption_and_signing", flags);
    }
}
