// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod client_connected_reducer;
pub mod init_encryption_and_signing_reducer;
pub mod update_encryption_keys_reducer;
pub mod user_table;
pub mod user_type;

pub use client_connected_reducer::{
    client_connected, set_flags_for_client_connected, ClientConnectedCallbackId,
};
pub use init_encryption_and_signing_reducer::{
    init_encryption_and_signing, set_flags_for_init_encryption_and_signing,
    InitEncryptionAndSigningCallbackId,
};
pub use update_encryption_keys_reducer::{
    set_flags_for_update_encryption_keys, update_encryption_keys,
    UpdateEncryptionKeysCallbackId,
};
pub use user_table::*;
pub use user_type::User;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClientConnected,
    InitEncryptionAndSigning {
        public_key: String,
        encrypted_private_key: String,
        encrypted_backup_key: String,
        public_signing_key: String,
        encrypted_private_signing_key: String,
        encrypted_private_backup_signing_key: String,
        argon_salt: String,
    },
    UpdateEncryptionKeys {
        new_encrypted_private_key: String,
        new_encrypted_private_signing_key: String,
        new_argon_salt: String,
        signature_base_64: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    /// Returns the canonical reducer name for this `Reducer` variant.
    ///
    /// The returned string is the static name used by the Spacetime protocol to
    /// identify which reducer is being invoked:
    /// - `ClientConnected` -> `"client_connected"`
    /// - `InitEncryptionAndSigning` -> `"init_encryption_and_signing"`
    /// - `UpdateEncryptionKeys` -> `"update_encryption_keys"`
    ///
    /// # Examples
    ///
    /// ```
    /// let name = Reducer::ClientConnected.reducer_name();
    /// assert_eq!(name, "client_connected");
    /// ```
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClientConnected => "client_connected",
            Reducer::InitEncryptionAndSigning { .. } => {
                "init_encryption_and_signing"
            }
            Reducer::UpdateEncryptionKeys { .. } => "update_encryption_keys",
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    /// Converts a `__ws::ReducerCallInfo<__ws::BsatnFormat>` into a `Reducer`.
    ///
    /// Matches `value.reducer_name` against the module's reducer names and parses the
    /// accompanying `args` into the corresponding reducer variant. Returns an error
    /// if the reducer name is unknown or if argument parsing fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Given a `ReducerCallInfo` `info` received from the websocket layer:
    /// // let reducer = Reducer::try_from(info).expect("valid reducer call");
    /// ```
    fn try_from(
        value: __ws::ReducerCallInfo<__ws::BsatnFormat>,
    ) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
                        "client_connected" => Ok(__sdk::parse_reducer_args::<client_connected_reducer::ClientConnectedArgs>("client_connected", &value.args)?.into()),
            "init_encryption_and_signing" => Ok(__sdk::parse_reducer_args::<init_encryption_and_signing_reducer::InitEncryptionAndSigningArgs>("init_encryption_and_signing", &value.args)?.into()),
            "update_encryption_keys" => Ok(__sdk::parse_reducer_args::<update_encryption_keys_reducer::UpdateEncryptionKeysArgs>("update_encryption_keys", &value.args)?.into()),
            unknown => Err(__sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo").into()),
}
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    user: __sdk::TableUpdate<User>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    /// Converts a raw WebSocket `DatabaseUpdate<__ws::BsatnFormat>` into this module's `DbUpdate`.
    ///
    /// Only known tables are accepted; each recognized table's updates are parsed and appended to the
    /// corresponding `DbUpdate` field. Currently the only supported table name is `"user"`, which is
    /// parsed with `user_table::parse_table_update`.
    ///
    /// Returns an `InternalError::unknown_name` (propagated as the `TryFrom` error) if an unknown
    /// table name is encountered.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// // Construct a raw update (example shape; actual construction depends on the __ws types)
    /// let raw = __ws::DatabaseUpdate { tables: vec![] };
    /// let db_update = module_bindings::DbUpdate::try_from(raw).unwrap();
    /// ```
    fn try_from(
        raw: __ws::DatabaseUpdate<__ws::BsatnFormat>,
    ) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    /// Applies this database update to the provided client cache and returns the resulting applied diff.
    ///
    /// The returned `AppliedDiff` describes which rows in the module's tables were inserted, updated,
    /// or removed as a result of applying this update. This operation mutates `cache`.
    ///
    /// # Examples
    ///
    /// ```
    /// // Create a client cache and an empty update, then apply it.
    /// let mut cache: __sdk::ClientCache<RemoteModule> = __sdk::ClientCache::default();
    /// let update = DbUpdate::default();
    /// let applied: AppliedDiff<'_> = update.apply_to_client_cache(&mut cache);
    /// // With an empty update, no rows should be affected.
    /// assert!(applied.user.is_empty());
    /// ```
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    user: __sdk::TableAppliedDiff<'r, User>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    /// Invoke registered per-row callbacks for the `user` table using this applied diff.
    ///
    /// This will call any table row callbacks that were registered for the "user" table,
    /// passing each per-row change contained in `self.user` along with the provided event context.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// // `applied_diff` is an AppliedDiff produced by applying a DbUpdate,
    /// // `event_ctx` is the current EventContext, and `callbacks` is the DbCallbacks registry.
    /// // The call below will forward row-level changes for the "user" table to registered callbacks.
    /// // applied_diff.invoke_row_callbacks(&event_ctx, &mut callbacks);
    /// ```
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    /// Returns a reference to the connection's database view.
    ///
    /// The returned view exposes table accessors for this remote module (e.g. the `user` table).
    ///
    /// # Examples
    ///
    /// ```
    /// let db_view = conn.db();
    /// // use `db_view` to access table APIs, e.g. `db_view.user()`
    /// ```
    fn db(&self) -> &Self::DbView {
        &self.db
    }
    /// Returns a reference to the reducers view for this database connection.
    ///
    /// The returned value provides access to reducer-related operations (e.g., registering
    /// reducer callbacks or setting reducer flags) for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// let conn = DbConnection::builder().build();
    /// let reducers = conn.reducers();
    /// // Use `reducers` to register callbacks or interact with reducers.
    /// let _ = reducers;
    /// ```
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    /// Returns a reference to the connection's SetReducerFlags view.
    ///
    /// This view is used to set or modify reducer flags for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module.
    /// let flags = conn.set_reducer_flags();
    /// // `flags` can now be used to set reducer-specific flags.
    /// ```
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Disconnects the underlying database connection.
    ///
    /// Attempts to close the active connection and returns an error if the disconnect fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Assuming `conn` is an active `DbConnection`
    /// conn.disconnect().expect("failed to disconnect");
    /// ```
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    /// Creates a new subscription builder tied to this connection.
    ///
    /// The returned builder is preconfigured to operate for this module's connection and can be
    /// used to construct and start subscriptions.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module
    /// let builder = conn.subscription_builder();
    /// // configure and use `builder`...
    /// ```
    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    /// Returns the current connection identity for this context, if available.
    ///
    /// The identity is present when the underlying connection is authenticated/connected;
    /// returns `None` when there is no active identity.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` can be a `DbConnection` or any event/context type that exposes `try_identity()`.
    /// let maybe_id = ctx.try_identity();
    /// if let Some(id) = maybe_id {
    ///     // use `id`...
    ///     let _ = id.to_string();
    /// }
    /// ```
    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    /// Returns the connection identifier for this DbConnection.
    ///
    /// The returned `__sdk::ConnectionId` uniquely identifies the active connection (if any).
    ///
    /// # Examples
    ///
    /// ```
    /// let id = db_connection.connection_id();
    /// // `id` can be compared or logged as needed
    /// ```
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl DbConnection {
    /// Create a new DbConnectionBuilder for this remote module.
    ///
    /// Returns a fresh [`__sdk::DbConnectionBuilder<RemoteModule>`] preconfigured for building
    /// a connection to the RemoteModule. See [`__sdk::DbConnectionBuilder`] for available
    /// configuration and how to establish the connection.
    ///
    /// # Examples
    ///
    /// ```
    /// let builder = builder();
    /// // configure `builder` (e.g. endpoint, credentials) then call its build method.
    /// ```
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// Process a single pending WebSocket message if one is available.
    ///
    /// Returns `Ok(true)` when a message was processed, `Ok(false)` when the incoming
    /// queue was empty, or an `Err` if the connection has been disconnected.
    /// Normal (intentional) disconnects will produce an error that can be downcast to
    /// `__sdk::DisconnectedError`.
    ///
    /// This is a low-level scheduling primitive for advanced users. Most callers
    /// should use `Self::frame_tick()` each frame to drain the queue when time is
    /// available. Callers that use this function typically loop until it returns
    /// `false` or until they have exhausted their processing time allotment.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// // Process messages until the queue is empty.
    /// // `conn` is a `DbConnection`-like value.
    /// while let Ok(true) = conn.advance_one_message() {
    ///     // handled one message; continue
    /// }
    /// ```
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process any pending WebSocket messages without blocking the current thread.
    ///
    /// This processes all queued incoming WebSocket frames/messages for the connection and
    /// returns immediately; it does not await asynchronous work or block waiting for new data.
    /// Any processing errors are returned as a `__sdk::Result::Err`.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` (or any type exposing `frame_tick`)
    /// let _ = conn.frame_tick().expect("frame tick failed");
    /// ```
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawns a background thread that continuously processes incoming WebSocket messages for this connection.
    ///
    /// The returned `JoinHandle` can be used to wait for the thread to finish. The background thread runs until
    /// the connection is disconnected or the underlying runtime stops.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// // `conn` is a `DbConnection` built via `DbConnection::builder()`.
    /// let conn = /* obtain a DbConnection */ unimplemented!();
    /// let handle = conn.run_threaded();
    /// // ... use the connection from other threads ...
    /// handle.join().expect("thread panicked");
    /// ```
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Runs the connection's asynchronous processing loop, awaiting until the connection ends or an error occurs.
    ///
    /// This processes incoming WebSocket messages on the current connection and returns when the loop completes.
    ///
    /// # Examples
    ///
    /// ```no_run
    /// // `conn` is a previously built and connected `DbConnection`.
    /// // Await the background processing loop to run until completion:
    /// // conn.run_async().await?;
    /// ```
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    /// Create a new DbConnection that shares the given internal database context.
    ///
    /// The resulting connection contains `db`, `reducers`, and `set_reducer_flags` views
    /// which all hold clones of the provided `__sdk::DbContextImpl<RemoteModule>` and
    /// the original `imp` is stored for operations requiring ownership.
    ///
    /// # Examples
    ///
    /// ```
    /// // `imp` is an internal __sdk::DbContextImpl<RemoteModule> provided by the SDK.
    /// let conn = DbConnection::new(imp);
    /// // The connection's activity state is delegated to the underlying context.
    /// let _ = conn.is_active();
    /// ```
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    /// Creates a SubscriptionHandle wrapping the provided internal implementation.
    ///
    /// This is a simple constructor that takes an SDK-internal `SubscriptionHandleImpl<RemoteModule>`
    /// and returns the public `SubscriptionHandle` wrapper.
    ///
    /// # Examples
    ///
    /// ```
    /// // Obtain the internal implementation from the SDK (e.g., from a subscription result).
    /// // let imp: __sdk::SubscriptionHandleImpl<RemoteModule> = /* ... */;
    /// // let handle = SubscriptionHandle::new(imp);
    /// ```
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from this subscription and invoke `on_end` once its rows are removed from the client cache.
    ///
    /// This consumes the handle, requests the server to end the subscription, and arranges for `on_end` to be
    /// called when the subscription has fully ended and all associated rows have been evicted from the local cache.
    ///
    /// # Examples
    ///
    /// ```
    /// # use app::module_bindings::SubscriptionHandle;
    /// # use app::module_bindings as bindings;
    /// let handle: SubscriptionHandle = unimplemented!();
    /// // `on_end` will be called when the subscription is fully ended and its rows removed.
    /// handle.unsubscribe_then(Box::new(|_ctx| {
    ///     // cleanup work here
    /// })).unwrap();
    /// ```
    fn unsubscribe_then(
        self,
        on_end: __sdk::OnEndedCallback<RemoteModule>,
    ) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    /// Unsubscribes from the remote subscription, dropping the handle.
    ///
    /// Returns Ok(()) on success or an error if the unsubscribe operation fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // `handle` is a SubscriptionHandle obtained from a subscription API.
    /// // Unsubscribe and propagate errors (if any).
    /// handle.unsubscribe().unwrap();
    /// ```
    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    /// Returns a reference to the contained event.
    ///
    /// This accessor provides read-only access to the `event` carried by the context.
    ///
    /// # Examples
    ///
    /// ```
    /// // given `ctx` is an event context (e.g. `EventContext`)
    /// // let ctx: EventContext = ...;
    /// // let event_ref = ctx.event();
    /// ```
    fn event(&self) -> &Self::Event {
        &self.event
    }
    /// Creates a new EventContext that wraps the given database context implementation and event.
    ///
    /// The returned context provides `db`, `reducers`, and `set_reducer_flags` views backed by clones
    /// of `imp`, and stores the provided `event`.
    ///
    /// # Examples
    ///
    /// ```
    /// let ctx = EventContext::new(imp, event);
    /// // ctx.db, ctx.reducers, and ctx.set_reducer_flags are available and backed by `imp`.
    /// ```
    fn new(
        imp: __sdk::DbContextImpl<RemoteModule>,
        event: Self::Event,
    ) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    /// Returns a reference to the connection's database view.
    ///
    /// The returned view exposes table accessors for this remote module (e.g. the `user` table).
    ///
    /// # Examples
    ///
    /// ```
    /// let db_view = conn.db();
    /// // use `db_view` to access table APIs, e.g. `db_view.user()`
    /// ```
    fn db(&self) -> &Self::DbView {
        &self.db
    }
    /// Returns a reference to the reducers view for this database connection.
    ///
    /// The returned value provides access to reducer-related operations (e.g., registering
    /// reducer callbacks or setting reducer flags) for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// let conn = DbConnection::builder().build();
    /// let reducers = conn.reducers();
    /// // Use `reducers` to register callbacks or interact with reducers.
    /// let _ = reducers;
    /// ```
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    /// Returns a reference to the connection's SetReducerFlags view.
    ///
    /// This view is used to set or modify reducer flags for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module.
    /// let flags = conn.set_reducer_flags();
    /// // `flags` can now be used to set reducer-specific flags.
    /// ```
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Disconnects the underlying database connection.
    ///
    /// Attempts to close the active connection and returns an error if the disconnect fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Assuming `conn` is an active `DbConnection`
    /// conn.disconnect().expect("failed to disconnect");
    /// ```
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    /// Creates a new subscription builder tied to this connection.
    ///
    /// The returned builder is preconfigured to operate for this module's connection and can be
    /// used to construct and start subscriptions.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module
    /// let builder = conn.subscription_builder();
    /// // configure and use `builder`...
    /// ```
    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    /// Returns the current connection identity for this context, if available.
    ///
    /// The identity is present when the underlying connection is authenticated/connected;
    /// returns `None` when there is no active identity.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` can be a `DbConnection` or any event/context type that exposes `try_identity()`.
    /// let maybe_id = ctx.try_identity();
    /// if let Some(id) = maybe_id {
    ///     // use `id`...
    ///     let _ = id.to_string();
    /// }
    /// ```
    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    /// Returns the connection identifier for this DbConnection.
    ///
    /// The returned `__sdk::ConnectionId` uniquely identifies the active connection (if any).
    ///
    /// # Examples
    ///
    /// ```
    /// let id = db_connection.connection_id();
    /// // `id` can be compared or logged as needed
    /// ```
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    /// Returns a reference to the contained event.
    ///
    /// This accessor provides read-only access to the `event` carried by the context.
    ///
    /// # Examples
    ///
    /// ```
    /// // given `ctx` is an event context (e.g. `EventContext`)
    /// // let ctx: EventContext = ...;
    /// // let event_ref = ctx.event();
    /// ```
    fn event(&self) -> &Self::Event {
        &self.event
    }
    /// Creates a new EventContext that wraps the given database context implementation and event.
    ///
    /// The returned context provides `db`, `reducers`, and `set_reducer_flags` views backed by clones
    /// of `imp`, and stores the provided `event`.
    ///
    /// # Examples
    ///
    /// ```
    /// let ctx = EventContext::new(imp, event);
    /// // ctx.db, ctx.reducers, and ctx.set_reducer_flags are available and backed by `imp`.
    /// ```
    fn new(
        imp: __sdk::DbContextImpl<RemoteModule>,
        event: Self::Event,
    ) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    /// Returns a reference to the connection's database view.
    ///
    /// The returned view exposes table accessors for this remote module (e.g. the `user` table).
    ///
    /// # Examples
    ///
    /// ```
    /// let db_view = conn.db();
    /// // use `db_view` to access table APIs, e.g. `db_view.user()`
    /// ```
    fn db(&self) -> &Self::DbView {
        &self.db
    }
    /// Returns a reference to the reducers view for this database connection.
    ///
    /// The returned value provides access to reducer-related operations (e.g., registering
    /// reducer callbacks or setting reducer flags) for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// let conn = DbConnection::builder().build();
    /// let reducers = conn.reducers();
    /// // Use `reducers` to register callbacks or interact with reducers.
    /// let _ = reducers;
    /// ```
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    /// Returns a reference to the connection's SetReducerFlags view.
    ///
    /// This view is used to set or modify reducer flags for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module.
    /// let flags = conn.set_reducer_flags();
    /// // `flags` can now be used to set reducer-specific flags.
    /// ```
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Disconnects the underlying database connection.
    ///
    /// Attempts to close the active connection and returns an error if the disconnect fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Assuming `conn` is an active `DbConnection`
    /// conn.disconnect().expect("failed to disconnect");
    /// ```
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    /// Creates a new subscription builder tied to this connection.
    ///
    /// The returned builder is preconfigured to operate for this module's connection and can be
    /// used to construct and start subscriptions.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module
    /// let builder = conn.subscription_builder();
    /// // configure and use `builder`...
    /// ```
    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    /// Returns the current connection identity for this context, if available.
    ///
    /// The identity is present when the underlying connection is authenticated/connected;
    /// returns `None` when there is no active identity.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` can be a `DbConnection` or any event/context type that exposes `try_identity()`.
    /// let maybe_id = ctx.try_identity();
    /// if let Some(id) = maybe_id {
    ///     // use `id`...
    ///     let _ = id.to_string();
    /// }
    /// ```
    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    /// Returns the connection identifier for this DbConnection.
    ///
    /// The returned `__sdk::ConnectionId` uniquely identifies the active connection (if any).
    ///
    /// # Examples
    ///
    /// ```
    /// let id = db_connection.connection_id();
    /// // `id` can be compared or logged as needed
    /// ```
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    /// Returns a reference to the context's event payload.
    ///
    /// For contexts that carry no event data, the event type is `()` and this
    /// returns a reference to the unit value.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` is a context type whose `Event` associated type is `()`.
    /// // let ctx: SubscriptionEventContext = ...;
    /// // assert_eq!(ctx.event(), &());
    /// ```
    fn event(&self) -> &Self::Event {
        &()
    }
    /// Creates a new context instance from a database context implementation and an event.
    ///
    /// The `imp` is stored and cloned into the contained `db`, `reducers`, and
    /// `set_reducer_flags` views. The `event` parameter is accepted to match the
    /// trait signature; some context types may ignore it (hence the leading `_`).
    ///
    /// # Examples
    ///
    /// ```
    /// // `imp` and `event` are provided by the runtime/SDK.
    /// let ctx = EventContext::new(imp, event);
    /// ```
    fn new(
        imp: __sdk::DbContextImpl<RemoteModule>,
        _event: Self::Event,
    ) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    /// Returns a reference to the connection's database view.
    ///
    /// The returned view exposes table accessors for this remote module (e.g. the `user` table).
    ///
    /// # Examples
    ///
    /// ```
    /// let db_view = conn.db();
    /// // use `db_view` to access table APIs, e.g. `db_view.user()`
    /// ```
    fn db(&self) -> &Self::DbView {
        &self.db
    }
    /// Returns a reference to the reducers view for this database connection.
    ///
    /// The returned value provides access to reducer-related operations (e.g., registering
    /// reducer callbacks or setting reducer flags) for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// let conn = DbConnection::builder().build();
    /// let reducers = conn.reducers();
    /// // Use `reducers` to register callbacks or interact with reducers.
    /// let _ = reducers;
    /// ```
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    /// Returns a reference to the connection's SetReducerFlags view.
    ///
    /// This view is used to set or modify reducer flags for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module.
    /// let flags = conn.set_reducer_flags();
    /// // `flags` can now be used to set reducer-specific flags.
    /// ```
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Disconnects the underlying database connection.
    ///
    /// Attempts to close the active connection and returns an error if the disconnect fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Assuming `conn` is an active `DbConnection`
    /// conn.disconnect().expect("failed to disconnect");
    /// ```
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    /// Creates a new subscription builder tied to this connection.
    ///
    /// The returned builder is preconfigured to operate for this module's connection and can be
    /// used to construct and start subscriptions.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module
    /// let builder = conn.subscription_builder();
    /// // configure and use `builder`...
    /// ```
    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    /// Returns the current connection identity for this context, if available.
    ///
    /// The identity is present when the underlying connection is authenticated/connected;
    /// returns `None` when there is no active identity.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` can be a `DbConnection` or any event/context type that exposes `try_identity()`.
    /// let maybe_id = ctx.try_identity();
    /// if let Some(id) = maybe_id {
    ///     // use `id`...
    ///     let _ = id.to_string();
    /// }
    /// ```
    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    /// Returns the connection identifier for this DbConnection.
    ///
    /// The returned `__sdk::ConnectionId` uniquely identifies the active connection (if any).
    ///
    /// # Examples
    ///
    /// ```
    /// let id = db_connection.connection_id();
    /// // `id` can be compared or logged as needed
    /// ```
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    /// Returns a reference to the contained event.
    ///
    /// This accessor provides read-only access to the `event` carried by the context.
    ///
    /// # Examples
    ///
    /// ```
    /// // given `ctx` is an event context (e.g. `EventContext`)
    /// // let ctx: EventContext = ...;
    /// // let event_ref = ctx.event();
    /// ```
    fn event(&self) -> &Self::Event {
        &self.event
    }
    /// Creates a new EventContext that wraps the given database context implementation and event.
    ///
    /// The returned context provides `db`, `reducers`, and `set_reducer_flags` views backed by clones
    /// of `imp`, and stores the provided `event`.
    ///
    /// # Examples
    ///
    /// ```
    /// let ctx = EventContext::new(imp, event);
    /// // ctx.db, ctx.reducers, and ctx.set_reducer_flags are available and backed by `imp`.
    /// ```
    fn new(
        imp: __sdk::DbContextImpl<RemoteModule>,
        event: Self::Event,
    ) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;

    /// Returns a reference to the connection's database view.
    ///
    /// The returned view exposes table accessors for this remote module (e.g. the `user` table).
    ///
    /// # Examples
    ///
    /// ```
    /// let db_view = conn.db();
    /// // use `db_view` to access table APIs, e.g. `db_view.user()`
    /// ```
    fn db(&self) -> &Self::DbView {
        &self.db
    }
    /// Returns a reference to the reducers view for this database connection.
    ///
    /// The returned value provides access to reducer-related operations (e.g., registering
    /// reducer callbacks or setting reducer flags) for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// let conn = DbConnection::builder().build();
    /// let reducers = conn.reducers();
    /// // Use `reducers` to register callbacks or interact with reducers.
    /// let _ = reducers;
    /// ```
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    /// Returns a reference to the connection's SetReducerFlags view.
    ///
    /// This view is used to set or modify reducer flags for the remote module.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module.
    /// let flags = conn.set_reducer_flags();
    /// // `flags` can now be used to set reducer-specific flags.
    /// ```
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    /// Returns true if the underlying database connection/context is currently active.
    ///
    /// This reflects the internal connection state exposed by the implementation.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `conn` is a DbConnection or other DbContext-backed value.
    /// // let conn = /* obtain connection */;
    /// // assert!(conn.is_active());
    /// ```
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Disconnects the underlying database connection.
    ///
    /// Attempts to close the active connection and returns an error if the disconnect fails.
    ///
    /// # Examples
    ///
    /// ```
    /// // Assuming `conn` is an active `DbConnection`
    /// conn.disconnect().expect("failed to disconnect");
    /// ```
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    /// Creates a new subscription builder tied to this connection.
    ///
    /// The returned builder is preconfigured to operate for this module's connection and can be
    /// used to construct and start subscriptions.
    ///
    /// # Examples
    ///
    /// ```
    /// // `conn` is a `DbConnection` for this module
    /// let builder = conn.subscription_builder();
    /// // configure and use `builder`...
    /// ```
    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    /// Returns the current connection identity for this context, if available.
    ///
    /// The identity is present when the underlying connection is authenticated/connected;
    /// returns `None` when there is no active identity.
    ///
    /// # Examples
    ///
    /// ```
    /// // `ctx` can be a `DbConnection` or any event/context type that exposes `try_identity()`.
    /// let maybe_id = ctx.try_identity();
    /// if let Some(id) = maybe_id {
    ///     // use `id`...
    ///     let _ = id.to_string();
    /// }
    /// ```
    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    /// Returns the connection identifier for this DbConnection.
    ///
    /// The returned `__sdk::ConnectionId` uniquely identifies the active connection (if any).
    ///
    /// # Examples
    ///
    /// ```
    /// let id = db_connection.connection_id();
    /// // `id` can be compared or logged as needed
    /// ```
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    /// Registers this module's tables with the given client cache.
    ///
    /// This installs all table schemas and handlers required by the module into the provided
    /// client cache so incoming database updates can be parsed and applied.
    ///
    /// # Examples
    ///
    /// ```
    /// let mut cache = __sdk::ClientCache::<module_bindings::RemoteModule>::new();
    /// module_bindings::RemoteModule::register_tables(&mut cache);
    /// ```
    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        user_table::register_table(client_cache);
    }
}
