// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit f497e53c3710ca5b52873eb6ec72e148a22541d6).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(
    __lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug,
)]
#[sats(crate = __lib)]
pub(super) struct UpdateEncryptionKeysArgs {
    pub new_encrypted_private_key: String,
    pub new_encrypted_private_signing_key: String,
    pub new_argon_salt: String,
    pub signature_base_64: String,
}

impl From<UpdateEncryptionKeysArgs> for super::Reducer {
    fn from(args: UpdateEncryptionKeysArgs) -> Self {
        Self::UpdateEncryptionKeys {
            new_encrypted_private_key: args.new_encrypted_private_key,
            new_encrypted_private_signing_key: args
                .new_encrypted_private_signing_key,
            new_argon_salt: args.new_argon_salt,
            signature_base_64: args.signature_base_64,
        }
    }
}

impl __sdk::InModule for UpdateEncryptionKeysArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateEncryptionKeysCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_encryption_keys`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_encryption_keys {
    /// Request that the remote module invoke the reducer `update_encryption_keys` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_encryption_keys`] callbacks.
    fn update_encryption_keys(
        &self,
        new_encrypted_private_key: String,
        new_encrypted_private_signing_key: String,
        new_argon_salt: String,
        signature_base_64: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_encryption_keys`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateEncryptionKeysCallbackId`] can be passed to [`Self::remove_on_update_encryption_keys`]
    /// to cancel the callback.
    fn on_update_encryption_keys(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> UpdateEncryptionKeysCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_encryption_keys`],
    /// causing it not to run in the future.
    fn remove_on_update_encryption_keys(
        &self,
        callback: UpdateEncryptionKeysCallbackId,
    );
}

impl update_encryption_keys for super::RemoteReducers {
    fn update_encryption_keys(
        &self,
        new_encrypted_private_key: String,
        new_encrypted_private_signing_key: String,
        new_argon_salt: String,
        signature_base_64: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_encryption_keys",
            UpdateEncryptionKeysArgs {
                new_encrypted_private_key,
                new_encrypted_private_signing_key,
                new_argon_salt,
                signature_base_64,
            },
        )
    }
    fn on_update_encryption_keys(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> UpdateEncryptionKeysCallbackId {
        UpdateEncryptionKeysCallbackId(self.imp.on_reducer(
            "update_encryption_keys",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateEncryptionKeys {
                                    new_encrypted_private_key,
                                    new_encrypted_private_signing_key,
                                    new_argon_salt,
                                    signature_base_64,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    new_encrypted_private_key,
                    new_encrypted_private_signing_key,
                    new_argon_salt,
                    signature_base_64,
                )
            }),
        ))
    }
    fn remove_on_update_encryption_keys(
        &self,
        callback: UpdateEncryptionKeysCallbackId,
    ) {
        self.imp
            .remove_on_reducer("update_encryption_keys", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_encryption_keys`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_encryption_keys {
    /// Set the call-reducer flags for the reducer `update_encryption_keys` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_encryption_keys(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_encryption_keys for super::SetReducerFlags {
    fn update_encryption_keys(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_encryption_keys", flags);
    }
}
