// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(
    __lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug,
)]
#[sats(crate = __lib)]
pub(super) struct UpdateEncryptionKeysArgs {
    pub new_encrypted_private_key: String,
    pub new_encrypted_private_signing_key: String,
    pub new_argon_salt: String,
    pub signature_base_64: String,
}

impl From<UpdateEncryptionKeysArgs> for super::Reducer {
    /// Convert `UpdateEncryptionKeysArgs` into the corresponding `Reducer::UpdateEncryptionKeys` variant.
    ///
    /// # Examples
    ///
    /// ```
    /// let args = UpdateEncryptionKeysArgs {
    ///     new_encrypted_private_key: "key".into(),
    ///     new_encrypted_private_signing_key: "signing".into(),
    ///     new_argon_salt: "salt".into(),
    ///     signature_base_64: "sig".into(),
    /// };
    /// let reducer: super::Reducer = args.into();
    /// match reducer {
    ///     super::Reducer::UpdateEncryptionKeys { new_encrypted_private_key, new_encrypted_private_signing_key, new_argon_salt, signature_base_64 } => {
    ///         assert_eq!(new_encrypted_private_key, "key");
    ///         assert_eq!(new_encrypted_private_signing_key, "signing");
    ///         assert_eq!(new_argon_salt, "salt");
    ///         assert_eq!(signature_base_64, "sig");
    ///     }
    ///     _ => panic!("unexpected reducer variant"),
    /// }
    /// ```
    fn from(args: UpdateEncryptionKeysArgs) -> Self {
        Self::UpdateEncryptionKeys {
            new_encrypted_private_key: args.new_encrypted_private_key,
            new_encrypted_private_signing_key: args
                .new_encrypted_private_signing_key,
            new_argon_salt: args.new_argon_salt,
            signature_base_64: args.signature_base_64,
        }
    }
}

impl __sdk::InModule for UpdateEncryptionKeysArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateEncryptionKeysCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_encryption_keys`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_encryption_keys {
    /// Request that the remote module invoke the reducer `update_encryption_keys` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_encryption_keys`] callbacks.
    fn update_encryption_keys(
        &self,
        new_encrypted_private_key: String,
        new_encrypted_private_signing_key: String,
        new_argon_salt: String,
        signature_base_64: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_encryption_keys`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateEncryptionKeysCallbackId`] can be passed to [`Self::remove_on_update_encryption_keys`]
    /// to cancel the callback.
    fn on_update_encryption_keys(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> UpdateEncryptionKeysCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_encryption_keys`],
    /// causing it not to run in the future.
    fn remove_on_update_encryption_keys(
        &self,
        callback: UpdateEncryptionKeysCallbackId,
    );
}

impl update_encryption_keys for super::RemoteReducers {
    /// Requests the remote module to invoke the `update_encryption_keys` reducer with new encrypted keys and signature.
    ///
    /// Sends the given encrypted private key, encrypted private signing key, Argon salt, and signature to the remote reducer.
    /// Returns Ok(()) if the request was successfully sent; otherwise returns an error from the SDK.
    ///
    /// # Examples
    ///
    /// ```
    /// # // `remote` is an instance implementing the `update_encryption_keys` extension (e.g., RemoteReducers).
    /// # fn example_call(remote: &impl update_encryption_keys) -> __sdk::Result<()> {
    /// remote.update_encryption_keys(
    ///     "enc_priv_key".to_string(),
    ///     "enc_signing_key".to_string(),
    ///     "argon_salt".to_string(),
    ///     "signature_base64".to_string(),
    /// )?;
    /// # Ok(())
    /// # }
    /// ```
    fn update_encryption_keys(
        &self,
        new_encrypted_private_key: String,
        new_encrypted_private_signing_key: String,
        new_argon_salt: String,
        signature_base_64: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_encryption_keys",
            UpdateEncryptionKeysArgs {
                new_encrypted_private_key,
                new_encrypted_private_signing_key,
                new_argon_salt,
                signature_base_64,
            },
        )
    }
    /// Registers a callback to be invoked when the `update_encryption_keys` reducer is triggered.
    ///
    /// The provided callback will be called with:
    /// - a reference to the reducer event context, and
    /// - references to the four string fields: `new_encrypted_private_key`, `new_encrypted_private_signing_key`,
    ///   `new_argon_salt`, and `signature_base_64`.
    ///
    /// Returns an `UpdateEncryptionKeysCallbackId` which can be used to remove the callback later.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// // `remote` implements the `update_encryption_keys` extension trait.
    /// let cb_id = remote.on_update_encryption_keys(|ctx, new_key, new_signing_key, argon_salt, sig_b64| {
    ///     // handle the update; `new_key`, `new_signing_key`, `argon_salt`, and `sig_b64` are &String
    ///     println!("Received new keys: {}, {}", new_key, new_signing_key);
    /// });
    /// // Later: remote.remove_on_update_encryption_keys(cb_id);
    /// ```
    fn on_update_encryption_keys(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &String,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> UpdateEncryptionKeysCallbackId {
        UpdateEncryptionKeysCallbackId(self.imp.on_reducer(
            "update_encryption_keys",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateEncryptionKeys {
                                    new_encrypted_private_key,
                                    new_encrypted_private_signing_key,
                                    new_argon_salt,
                                    signature_base_64,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    new_encrypted_private_key,
                    new_encrypted_private_signing_key,
                    new_argon_salt,
                    signature_base_64,
                )
            }),
        ))
    }
    /// Unregisters a previously registered callback for the `update_encryption_keys` reducer.
    ///
    /// The provided `callback` id (returned by `on_update_encryption_keys`) is removed so the callback
    /// will no longer be invoked when the reducer runs.
    ///
    /// # Examples
    ///
    /// ```
    /// // let reducers = /* instance of RemoteReducers */ ;
    /// // let callback_id = reducers.on_update_encryption_keys(|_ctx, a, b, c, d| { /* ... */ });
    /// // reducers.remove_on_update_encryption_keys(callback_id);
    /// ```
    fn remove_on_update_encryption_keys(
        &self,
        callback: UpdateEncryptionKeysCallbackId,
    ) {
        self.imp
            .remove_on_reducer("update_encryption_keys", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_encryption_keys`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_encryption_keys {
    /// Set the call-reducer flags for the reducer `update_encryption_keys` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_encryption_keys(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_encryption_keys for super::SetReducerFlags {
    /// Set call-reducer flags for the `update_encryption_keys` reducer.
    ///
    /// This configures how the remote reducer invocation is performed (e.g., retry, timeout,
    /// or delivery semantics) by applying the provided `__ws::CallReducerFlags` to the
    /// "update_encryption_keys" reducer.
    ///
    /// # Examples
    ///
    /// ```
    /// // Given an implementation of `SetReducerFlags` named `set_flags_impl`:
    /// // set_flags_impl.update_encryption_keys(__ws::CallReducerFlags::default());
    /// ```
    fn update_encryption_keys(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_encryption_keys", flags);
    }
}
