// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(
    __lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug,
)]
#[sats(crate = __lib)]
pub struct User {
    pub identity: __sdk::Identity,
    pub public_key: Option<String>,
    pub encrypted_private_key: Option<String>,
    pub encrypted_backup_key: Option<String>,
    pub public_signing_key: Option<String>,
    pub encrypted_private_signing_key: Option<String>,
    pub encrypted_private_backup_signing_key: Option<String>,
    pub argon_salt: Option<String>,
}

impl __sdk::InModule for User {
    type Module = super::RemoteModule;
}
